### ISSUE TITLE
Create an interactive figma prototype for showcase purposes

### ISSUE THREAD

**Issue by maht0rz** [galacticcouncil/Basilisk-ui-old#1004]
For the sake of presenting the work done on the design side before it is implemented, we have decided to provide an interactive/clickable prototype. This prototype will walk the user through one or more user flow(s), showcasing the most common use cases.

This ticket encompasses the following flow:

1. Select active account (select a wallet first ofc)
2. Navigate from the landing page to the wallet, see the empty asset list (with all available assets ofc)
3. Click transfer on DAI, go to cross chain, and the cross chain flow stops here (and we move back to asset list)
4. After cross chain transfer is done, you are back at the trade page but you now have the balance of what you transfered from the other chain
5. Click trade in the asset list for the thing you have as a balance
6. You're on the trade page now, with the asset in (top one) being the one you clicked on in the asset list
7. Click on the asset out asset selector, select BSX (this means you are buying BSX with the asset you bridged before - could be DAI)
8. Now you can press MAX on the top asset, it will fill in the balance you have bridged
9. In the trade info at the bottom, the tx fee must be shown as DAI, bcs thats your fee payment asset now - make sure to reflect this in the asset list so its obvious. WIth this being said, the amount filled in the form top balance input, must be your balance - tx fee so that your max button actually works as intended (can explain if unclear)
10. you click transfer, end up in the confirmation screen, go through it and broadcast it
11. notification about success, maybe even go to the notif center to see it again - end the flow here?

**Comment by samborek** [comment]
For review 
https://www.figma.com/proto/HZt2Xm6sfGWsI3vnnnaMC9/%F0%9F%A6%8E--Basilisk_V3.2-Michal?page-id=172%3A2376&node-id=6060%3A107089&viewport=373%2C-709%2C0.09&scaling=scale-down&starting-point-node-id=5851%3A151605

**Comment by maht0rz** [comment]
Feedback on the video uploaded by @samborek into Discord:

1. Time: 0:02  ![image.png](https://images.zenhubusercontent.com/61813e0eede4967ed5e35eb2/5a0c1f14-3df1-4b67-a3e5-377ca37690c9)
    - This button should not be disabled
2. Time: 0:04 ![image.png](https://images.zenhubusercontent.com/61813e0eede4967ed5e35eb2/be5ce4b1-1d50-4a04-9450-a8785be00bc6)
    - I'd suggest to change the copy to "I'm new to the Dotsama ecosystem" or instead of Dotsama ecosystem - Basilisk Chain
    - Why is one link a diff color? Is this intentional?
3.  Time: 0:06 ![image.png](https://images.zenhubusercontent.com/61813e0eede4967ed5e35eb2/eacde93a-c868-40e2-bb92-14d219701839)
    - 'Sign the transaction' might not be entirely applicable here, since the wallet connection popup has different copy, but i'd leave it as it is. Might raise questions in the audience
4. Time: 0:18 ![image.png](https://images.zenhubusercontent.com/61813e0eede4967ed5e35eb2/b97f6f3a-224c-48a4-a56b-eac1b051737c
     - 'Not enough balance' isn't accurate here, since the amounts are both 0, including the user's balance. This error is originally associated with user balance <> trade input balance
     - What would make sense is 'not enough fee balance' <-- something like that
 5. 0:18 ![image.png](https://images.zenhubusercontent.com/61813e0eede4967ed5e35eb2/9501cf29-c8de-47b2-b935-e41e9cb60dd2)
     - i'd change 'rate' to 'price'

6. 0:30 ![image.png](https://images.zenhubusercontent.com/61813e0eede4967ed5e35eb2/25577f0c-33c6-4ddb-8377-bdc9d12854a1)
     - address 'from' doesn't match the address in the mini wallet in the page header
     - 'your balance' should be 0 to be accurate
     - 'transaction cost' % i'd get either rid of or make it 0, unsure how exactly it should work so i assume it's % value of USD value the fee vs the balance input

 7. 0:36 ![image.png](https://images.zenhubusercontent.com/61813e0eede4967ed5e35eb2/80c8536d-ccdb-47e8-a57a-33d679d89942)
    - this copy could use some work, we're mentioning KSM specifically but the bridge support is for more assets than that etc. But it's probably not imporatnt at this stage

8. 0:42 ![image.png](https://images.zenhubusercontent.com/61813e0eede4967ed5e35eb2/d79d4946-c024-4279-b2ce-697343f8ee43)
    - if we wanted to be perfect, i'd 'inspect element' and turn 'Bifrost' into 'Basilisk' including the logo, need to know how perfect the video/prototype should be

9. 0:43 ![image.png](https://images.zenhubusercontent.com/61813e0eede4967ed5e35eb2/ec077a83-cf7a-4bc1-a4c6-708c58faffbf)
    - aUSD should not be shown here, this part isn't meant for displaying the fee payment asset, but rather the primary asset which needs to be selected manually, otherwise it defaults to BSX - i'd show 0 BSX

10.  0:44 ![image.png](https://images.zenhubusercontent.com/61813e0eede4967ed5e35eb2/3e1db280-8526-4e6d-8e60-8de4f2b40879)
    - is the (miss)alignment in the table intentional?

11. 0:54 ![image.png](https://images.zenhubusercontent.com/61813e0eede4967ed5e35eb2/a82936f9-b51c-47f9-8f9d-b1ebcd4ff3a8)
    - balances here should match the previous view of the asset list, e.g. BSX = 0

 12. 0:55 ![image.png](https://images.zenhubusercontent.com/61813e0eede4967ed5e35eb2/6b28f8e4-24bb-453b-ac71-88d5f194c139)
    - balance of BSX is correct here, assuming it will be 0 as outlined in previous feedback step (10.)
    - trade fees should be 0 BSX 
    - (bear with me) when you get navigated to the trade page from the asset list by clicking 'trade' on 'aUSD', it's placed in the position of the asset in, this means the 'trade' button in the asset list is 'sell', not 'buy'. If this is the case (which it can be for the sake of the demo) then the second asset 'asset out' should not be preselected. Which means that the transaction cost should be N/A and also the trade fee should be N/A. If the second asset gets selected in our flow, then the trade fee needs to be always paid in the asset that isn't inputted by the user. So if your flow is asset list (trade) -> navigate -> show aUSD at the top -> select XYZ at the bottom -> press MAX at the top -> then you can show the trade fee in the asset of 'you get' 

13. 0:59 ![image.png](https://images.zenhubusercontent.com/61813e0eede4967ed5e35eb2/fc670b28-6fe2-42e9-ae98-dd74dec3c7bb)
    - 'Slippage' should be 'Price Impact' and it should not be editable
    - 'Minimal amount you recieve' should not be approximate, but precise (drop the double tilde) + add the unit (BSX)
    - trade fees should be in BSX, as mentioned in the previous point
    - transaction fees should be in aUSD, this is your first bridged asset, therefore its set as the fee payment asset (which also means you need to lower the filled in max balance by the tx fee e.g. balance = 5000, fee = 10, max balance in the input = 4990
    - the same feedback is applicable for the confirmation screen info table

14. 1:15 ![image.png](https://images.zenhubusercontent.com/61813e0eede4967ed5e35eb2/ba0e3f1c-980e-4469-b83d-5be1a4e5abdf)
    - the notification should reflect the trade which has been done in the previous steps 
    - in the mini-wallet in the page header, keep BSX as the primary asset.

**Comment by Cubo25** [comment]
I have noticed some small graphical things so I just post screenshots here : 
This overlay of actions 
![Screenshot 2022-06-30 at 09.13.10.png](https://images.zenhubusercontent.com/61f9263bc6f1d203105662c6/791a3569-e5d6-41ea-90ec-94abcc28f1ac)
![image.png](https://images.zenhubusercontent.com/61f9263bc6f1d203105662c6/267144bc-d6c2-4473-a615-5a9c701a1014)
Alignment of the columns in the table 
![image.png](https://images.zenhubusercontent.com/61f9263bc6f1d203105662c6/94ffa056-09b4-49a8-8464-c1c463f2089c)
Share token overlay
![image.png](https://images.zenhubusercontent.com/61f9263bc6f1d203105662c6/d4e584b1-8d29-43a8-a164-94d0c719f0fe)

**Comment by samborek** [comment]
@Cubo25  great catch :D  Fixed, yet like I said the Prototype serves purpose of one flow.  hard to hit all of the spots but  fixed those issues

**Comment by samborek** [comment]
@maht0rz fixed most of those comments above but will disregard couple last ones as Kubo already showed it to bunch of people, this should be enough for now IMHO with that time investment. Thanks for help. 
Some of them should be transitioned to overall design and we should fix some of those problems. 

https://www.figma.com/proto/HZt2Xm6sfGWsI3vnnnaMC9/%F0%9F%A6%8E--Basilisk_V3.2-Michal?page-id=172%3A2376&node-id=5851%3A151605&viewport=373%2C-709%2C0.09&scaling=scale-down&starting-point-node-id=5851%3A151605

**Comment by maht0rz** [comment]
@jakubgregus marking as 'done'.
