### ISSUE TITLE
Bug: Basilisk UI - Buttons of 'install extensions modal' are not aligned

### ISSUE THREAD

**Issue by dmoka** [galacticcouncil/Basilisk-ui-old#1041]
### Description
The "install or enable" and "reload the page" buttons in the "INSTALL EXTENSION" modal are not aligned to the middle

Notion test case: https://www.notion.so/Account-Extension-18c415d452c249af858c55f5dcefc132#7f24c08401954ef292b59ab7ae11af75

### Expected Behaviour
They are aligned to the middle

### Actual Behaviour
They are aligned to left

![image.png](https://images.zenhubusercontent.com/6298a41aeaae3382ad1ea35a/f018149b-6eb4-4ef9-bffa-aa38e9c4a362)

### Possible Fix
Aligning them to middle

### Steps to Reproduce

Prerequisite: Extension not available in the browser

1. Go to Trade page
2. Click on connect account so the "INSTALL EXTENSION" modal is opened

### Context
Trying to install the extension and login to basilisk
### Your Environment

* Toolchain versions: 
* Version used: 8edcf46
* System type: 
* Operating System and version: Ubuntu 22.04
* System specs:

**Comment by Matehoo** [comment]
Issue fixed in 0.5

<img width="472" alt="Screenshot 2022-07-18 at 10 42 11" src="https://user-images.githubusercontent.com/55109377/179475107-ffb5a85b-5a9b-472f-adab-e6309ebc4b40.png">
