### ISSUE TITLE
Bug: nova wallet crashes app on confirmation screen

### ISSUE THREAD

**Issue by mrq1911** [galacticcouncil/Basilisk-ui-old#1056]

**Comment by jrafaelangarita** [comment]
https://user-images.githubusercontent.com/84519335/179381775-d21660b7-6ba1-4b92-b640-380a526ed355.mp4

**Comment by Cubo25** [comment]
Browser: nova browser
Version : 945586a
Status : ✅  pass 
Tested on Iphone everything seems to work
