### ISSUE TITLE
Bug: Select account popup selects account on copy account icon click

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/Basilisk-ui-old#1067]
If you click on copy account (account icon) while the active account selection is open. It will close and set the active account instead of copy to clipboard.

**Comment by Cubo25** [comment]
@jak-pan  pls can you provide what do you mean exactly ? Also I was not aware of this functionality "copy" in this window.

**Comment by dexterslabor** [comment]
I have fixed this and noticed another bug:

When clicking on Substrate account, it was copying the Basilisk encoded address and not the relay chain one starting with `5Grw...`

![image.png](https://images.zenhubusercontent.com/6188fb3dad80f64d846cbf9e/1d0eae21-9a38-47dc-912d-557241b5e1dc)

**Comment by maht0rz** [comment]
@dexterslabor isnt just your icloud handover clipboard acting up? it works for me in the PR you've made
