### ISSUE TITLE
Bug: if I start to place numbers in the token  when try to add liquidity, it does not take the order

### ISSUE THREAD

**Issue by jrafaelangarita** [galacticcouncil/Basilisk-ui-old#1081]
if I start to place numbers in the token B, when i will add liquidty to  pools, it does not take the order.

### Description
when trying to add liquidity, starting with token B, token A is not filled, even the problem "insufficient liquidity in token A" appears

### Expected Behaviuor
fill in the numbers of token b, and therefore its equivalent in Token A, for greater ease in adding liquidity (if the token with the lowest balance is in position b)

### Actual Behaviuor
It does not put the equivalent in token A, and I get the error "insufficient liquidity of token A)

Possible Fix
X

### Steps to Reproduce
Go to pools
Enter any amount on token B  first
Submit

User is able to do this action with all the pools, the matter is start on token B

### Context
I tried to add liquidity starting with token B, because it was easier to calculate based on that asset

![Screenshot_44](https://user-images.githubusercontent.com/84519335/180499122-ca088995-5731-4e67-9958-302a51edb20f.png)
![Screenshot_45](https://user-images.githubusercontent.com/84519335/180499128-02a847ed-a219-4e06-b0ed-ba3cd68ccf43.png)
![Screenshot_46](https://user-images.githubusercontent.com/84519335/180499129-d7d7f836-1ec2-4653-9bf1-57b6787eb45b.png)
 the order should not matter

**Comment by Cubo25** [comment]
@jrafaelangarita For now there is validation in place 
![image](https://user-images.githubusercontent.com/8873699/188477914-3254f320-0042-40be-a204-57a0057c06ba.png)
The whole new UX for this screen is in progress.
