### ISSUE TITLE
Bug: Talisman Wallet not supported unless Polkadot.js extension is installed

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/Basilisk-ui-old#1091]
Talisman wallet does not work at all if polkadot.js is not installed
### Description

Talisman wallet does not work at all if polkadot.js is not installed - it never pops up and app.basilisk.cloud never appears in the trusted sites list.
![image](https://user-images.githubusercontent.com/97540577/181540460-ef3ea09b-9f8a-45bc-b7fa-855f3499efdd.png)
![image](https://user-images.githubusercontent.com/97540577/181540803-96be374c-0938-49e3-be8b-05bbbed3aa0d.png)

### Expected Behavior

When connecting my wallet to app.basilisk.cloud for the first time by clicking the Connect Account button, it should cause the Talisman extension to pop up, allowing me to connect to the dapp.
### Actual Behavior

I am met with a message to install polkadot.js and Talisman does not pop up - I can not add app.basilisk.cloud to the list manually in Trusted Sites either.
### Steps to Reproduce

1.
2.
3.

### Your Environment

* Toolchain versions: 
* Version used:
* System type: 
* Operating System and version:
* System specs:

**Comment by lolmcshizz** [comment]
<img width="719" alt="image" src="https://user-images.githubusercontent.com/97540577/182834697-d82b026e-4652-41d5-a444-f8895abd543b.png">

**Comment by Cubo25** [comment]
Tested on https://github.com/galacticcouncil/Basilisk-ui/pull/1097 branch. 
LGTM ! 👍 
[chrome-capture-2022-7-15.webm](https://user-images.githubusercontent.com/8873699/184643602-0bb9d4f4-e58e-4185-8086-1f03b4e5c722.webm) 📹
![Screenshot 2022-08-15 at 15 24 19](https://user-images.githubusercontent.com/8873699/184643677-734767f3-a90f-41d5-9755-c952a2c9f34c.png) 📸
