### ISSUE TITLE
V0 Testnet

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/Basilisk-ui-old#113]
Crashes:
- [x] - Swap -> cancel
- [x] - URL paste wrong asset
- [ ] - Graph is broken with more than 2 pools looks like we're getting data from all the pools combined

Logic errors:
- [x] - Can't add . at the end of the input (prolly because bignumber conversion)
- [x] - Don't prefill 0 into the second asset field on load
- [x] - Clear second input after clearing active input
- [x] - When selecting granularity the value is briefly shown in the input itself
- [x] - There is a brief period of not loading but also no assets selected when loading the screen making loading dissapear and reappear in before<>after trade display
- [x] - Wallet bugs - If block comes during clearing account it's reselected, sometimes extension is not detected, sometimes account is not detected (race condition: active account is being refetched async, clearing happens and then refetch is finished and the account is set again)
- [x] - It takes 2 blocks to unlock the button (do we wait for finalized or inblock?)
- [x] - Disallow multiple transactions at the same time
- [x] - Add graph loading status
- [ ] - Clear / switch inputs when switching assets
- [ ] - show < / > symbols when the shown value is lower than the displayed granularity e.g. > 0.00%
- [x] - add assetId ordering to prevent fetching data when switching assets
- [ ] - when inputing assetIn and the calculated asset out is 0, we get minTradeLimit error, since assetOut isnt set. We should actually get maxTradeLimit error on assetIn (revisit guards when calculating amounts) (solution?: order validations depending on trade type / interacted with input)
- [x] - unreliable extension detection (implement retries when trying to detect the extension)
- [x] - when there is no account connected, trade balances are stuck at loading
- [x] - hide already selected asset (either in / out) in the trade form, this will prevent a state where both assets selected are the same.
Missing:
- [x] - Spot price rounding
- [ ] - Extract trade form things to components
- [x] - Balance from -> to + % change 
- [ ] - max button
- [x] - Help link
- [ ] - Copy address
- [x] - Asset icons
- [ ] - Error/Warn messages
- [x] - Y chart should be limited to ~80%? of height
- [x] - Fee payment estimate
- [ ] - Existential deposit handling
- [ ] - Tooltip with full amounts / address
- [x] - debug box
- [ ] - when more wallets have same account it shows only one as source of that acc but it's shown twice

Styling missing:
- [x] - Notifications
- [ ] - Error states in acc selector
- [x] - Error states
- [x] - Button ? + States
- [ ] - Asset selector polish
- [ ] - Loading states
- [ ] - Trade settings (+ smaller settings icon?) (checkbox --> 'auto' button)
- [ ] - hide unit selector when asset isn't selected (actually display '-' instead of hiding the whole unit selector)
- [ ] - clear account color
- [ ] - inline question mark / help + tooltip (e.g. what is slipapge?)

V0.1:
- [ ] - Refactor
- [ ] - Fee payment asset
- [ ] - Wallet page
- [ ]  - Wallet selection

**Comment by jak-pan** [comment]
We have some issue with reading graph data in the graph header. If moving mouse left->right I can only see peaks if I'm moving right -> left only valleys

![Screenshot 2022-03-02 at 20.40.26.png](https://images.zenhubusercontent.com/616633d5d0c80aec4c4476c9/b6dd4218-6999-4833-8a68-792b819cfc7e)

**Comment by mrq1911** [comment]
wallet selector formats Kusama addresses to the BSX ss58 instead of Kusama ones
![basilisk-testnet hydration cloud_feat_lbp-v1_app_](https://user-images.githubusercontent.com/2580779/157153546-2217edf5-f748-4c4f-b015-2cce966f2ab1.png)

**Comment by mrq1911** [comment]
the graph is advising to set valid pair even when it is just loading data

**Comment by jak-pan** [comment]
Switch pay with and you get for v0 do AB testing then decide (It will be really bad to change this after launch so we should get on it)

**Comment by jak-pan** [comment]
Can we close this? @Cubo25 @maht0rz

**Comment by Cubo25** [comment]
Closing due to clean up.
