### ISSUE TITLE
Bug: % change and graph should be red

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/Basilisk-ui-old#122]
% change under price and line graph should be red when negative
### Description

![unknown-2](https://user-images.githubusercontent.com/97540577/158479502-89a06716-77e0-4c43-8499-b7f88254e879.png)
As the change in price is negative (numba go down) - both the line graph and the number in brackets should be coloured red instead of green 
### Expected Behavior

Numba should be red
### Actual Behavior

Numba is green
### Possible Fix

Make numba go red
### Steps to Reproduce

1.
2.
3.

### Context

I feel sad because I was buying as numba was green but actually numba should be red so down tremendously - can devs do something?
### Your Environment

* Toolchain versions: 
* Version used:
* System type: 
* Operating System and version:
* System specs:

**Comment by jak-pan** [comment]
This is a correct behavior you are looking at a change from now (from the right) price is therefore larger at the point of your cursor and should be green

**Comment by lolmcshizz** [comment]
![image](https://user-images.githubusercontent.com/97540577/158569092-f045ff3b-902a-407a-9b38-a4a3357960fc.png)

Ignore the screenshot, I stole that from Matej - please see new screenshot where my cursor is not over the chart at all, as it is down during the time window in question I would expect this chart to be red

**Comment by lolmcshizz** [comment]
![image](https://user-images.githubusercontent.com/97540577/158569834-2cfd8bd4-59a2-4723-b43e-f8b96ecb9a68.png)
Interestingly on the BSX/ KSM chart it's how I would expect

**Comment by jak-pan** [comment]
Yes this is a bug but I think it is originating from a bug know about this but it's not logged yet @maht0rz fetching of historical data after long pause.

**Comment by Tbaut** [comment]
I got that one as well, everything is inverted, the positive is red, the negative is green, with or without the cursor above the graph

![image](https://user-images.githubusercontent.com/33178835/163273036-4d3eae90-14be-41bd-a5b5-2e276d3b18e3.png)
![image](https://user-images.githubusercontent.com/33178835/163273050-4bc3541d-2d7b-448e-baf9-955b8d1274f5.png)

**Comment by Cubo25** [comment]
Whole graph feature will be re-done and is not available in current version https://app.basilisk.cloud/
so the bug is not actual anymore.
