### ISSUE TITLE
Improve input field for the number of tokens to exchange

### ISSUE THREAD

**Issue by NormandieNiemen** [galacticcouncil/Basilisk-ui-old#125]
### Detailed Description

After entering the required number of tokens to complete the swap, if necessary, change the volume for the swap, the input field does not allow you to do this the first time, and you have to do this twice, since the value of the number of tokens does not change. I have attached a video of the process.
**Recording of process: [https://youtu.be/46m7tHqiiL4](https://youtu.be/46m7tHqiiL4)**

### Context

For me personally, this is sometimes inconvenient.

This will help avoid swaps with the wrong variables for some inattentive users.

### Possible Implementation

Please make sure that while updating the needed volume for trading, you do not have to select the input field twice and insert the appropriate numbers twice, since this may cause confusion for certain inattentive users.

**Comment by NormandieNiemen** [comment]
This also applies to those cases when you do not even select the entire field, but simply try to enter a number into the existing number of tokens for exchange in the input field.

**Comment by Cubo25** [comment]
Unable to reproduce in the newest version: https://app.basilisk.cloud/
