### ISSUE TITLE
Bug: 4 kilo bsx to 66 kilo?

### ISSUE THREAD

**Issue by CounselorGrk** [galacticcouncil/Basilisk-ui-old#128]
bXhewYbSzN5LEGRURF5MRVQvUsSPoGNFRYvQF3H98wngtCWdn

I think I traded 500 000 kilo DAI for 66 kilo BSX and it worked even though i had a starting balance of i believe 5 kilo DAI. Sorry if any of this is inaccurate i was clicking a bunch and fast lol
### Steps to Reproduce

1.
2.
3.

### Your Environment

* Toolchain versions: 
* Version used:
* System type: 
* Operating System and version:
* System specs:

**Comment by lolmcshizz** [comment]
Unable to reproduce - if you're able to reproduce the error again, please provide further information to help us reproduce
