### ISSUE TITLE
Bug: Microsoft EDGE Graph

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/Basilisk-ui-old#133]
Microsoft EDGE (I'm aware we aren't initially supporting this, but I am flagging none-the-less so we have it recorded) does not correctly display the trading graph
### Description

Microsoft EDGE (I'm aware we aren't initially supporting this, but I am flagging none-the-less so we have it recorded) does not correctly display the trading graph - images are shared below
### Expected Behavior

![image](https://user-images.githubusercontent.com/97540577/158571284-e1156280-1c59-4dcc-8968-6bcc8592cb33.png)
Graph as displayed in Google Chrome
### Actual Behavior

![image](https://user-images.githubusercontent.com/97540577/158571366-704f2938-bae8-40f9-8ead-e8154ca14e4b.png)
Graph as displayed in Microsoft Edge
### Steps to Reproduce

1.
2.
3.

### Your Environment

* Toolchain versions: 
* Version used:
* System type: 
* Operating System and version:
* System specs:

**Comment by jak-pan** [comment]
can you refresh the page and see if it's fixed?

**Comment by lolmcshizz** [comment]
![image](https://user-images.githubusercontent.com/97540577/158615873-66de21d2-2e5f-4871-8fb1-b184af1f9123.png)
Not all heroes wear capes ser

Fixed!

**Comment by jak-pan** [comment]
Ok this is the same issue as in the other one. Will close this as duplicate.
