### ISSUE TITLE
Bug: Transaction Failed (KSM/BSX)

### ISSUE THREAD

**Issue by Leemo94** [galacticcouncil/Basilisk-ui-old#135]
After initiating multiple swaps to acquire ~38.39 KSM, i tried to initiate a swap within the KSM/BSX pair, however, the transaction keeps failing.

### Description
Attempting to swap 38.38 KSM into BSX tokens on the testnet. However the transaction keeps failing. This happens with auto slippage enabled (3%), and slippage set to 50% (note: "current slippage" is at 0.39%). Smaller amounts of KSM do not work either. 

### Expected Behavior
DEX should swap KSM for BSX at current market rate.

### Actual Behavior
After signing the transaction, the transaction fails.
![image](https://user-images.githubusercontent.com/89027356/158641189-460af1ca-cbcb-4ee8-9391-3242076bb362.png)

### Steps to Reproduce
Account: bXgsgqEHwZdtpShnu8yL2dTSkAZQ5wApuqsr7B7s5TNg5ijZK
I initiated 5 transactions prior to this one (you may have to check the account address above).
Now when i try to swap KSM into BSX it does not work.

**Comment by Cubo25** [comment]
Unable to reproduce in the newest version: https://app.basilisk.cloud/.

This is already in production. No problems with swapping KSM for BSX or vice versa. 

Please try on the https://app.basilisk.cloud/ if still reproducible.
