### ISSUE TITLE
Add unit scale prefix selection setting

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/Basilisk-ui-old#136]
Several testers were concerned about using SI units prefixes used to scale the numbers displayed in the UI.

There are 4-6 options we can use in this case. Reasoning is to compress the numbers and ease reading of large or small numbers. Selected long SI standard was based on assumption everybody knows this from the base or high school but it seems to be wrong. The current design uses maximum 6 characters (1 000.00) + Unit prefix. Therefore we use units that scale by 3.

The options we have are:
Long Prefix: e.g. (micro, milli, kilo, mega, tera)
Short Prefix: (symbol) (u, m, k, M, T)
10^n: (10^-6, 10^-3, 10^3, 10^6, 10^12)

The other option is to re-style the UI to be able to accept longer units which will cause more visual bloat but might be more clear for more people:

Financial prefixes: (Millionth, Thousandth, Thousand, Million, Trillion)
Full numbers: 0.000001, 0.001, 1 000.00, 1 000 000.00, 1 000 000 000 000.00

The problem with this that it will be quite common to display such numbers and people are complaining already about the small font size. This means we need to do some magic here. 

We should create all of these options for displaying units and let people chose their preferred one (maybe in onboarding wizard?)

**Comment by jak-pan** [comment]
This is the problem we are trying to avoid https://matcha.xyz/markets/1/0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce/0x2260fac5e5542a773aa44fbcfedf7c193bc2c599
<img width="1209" alt="Screenshot 2022-03-17 at 20 32 10" src="https://user-images.githubusercontent.com/3409250/158881338-46dbb7f1-0e28-4f5c-9511-0fd036606433.png">

**Comment by faresar** [comment]
How about instead of selecting microbsx, the UI automatically selects the unit by itself when user enters, pastes more digits and when UI visually can no longer take in more numbers. This way the unit will always be base unit, but what is displayed to users shifts when its needed.

so the digit entry field can be shorter, and the digit display area will shift units to fit the limited space

shared this in telegram. Copying it here

**Comment by jak-pan** [comment]
> How about instead of selecting microbsx, the UI automatically selects the unit by itself when user enters, pastes more digits and when UI visually can no longer take in more numbers. This way the unit will always be base unit, but what is displayed to users shifts when its needed.
> 
> 
> 
> so the digit entry field can be shorter, and the digit display area will shift units to fit the limited space
> 
> 
> 
> shared this in telegram. Copying it here

Yeah that would be what I'd do intuitively but the problem is people don't understand SI prefixes. We're probably going to end up with a solution where you calculate significant digits based on value and round the rest while still being able to input precise amounts (this will be for display values) we're redesigning the ui to accommodate more digits tho right now because of this.

**Comment by Cubo25** [comment]
Closing due to clean up. This is outdated due to new version of Basilisk UI.
