### ISSUE TITLE
Bug: Frozen in transaction pending

### ISSUE THREAD

**Issue by CounselorGrk** [galacticcouncil/Basilisk-ui-old#138]
After submitting a trade and the sign transaction box prompt pops up, if I exit out of the sign transaction box without completing the transaction or entering my password the UI is stuck in transaction pending. 
### Expected Behavior

If Polkadot transaction box is closed, I expected for transaction pending to disappear or the transaction failed to appear.
### Actual Behavior

Instead, transaction pending was stuck on the screen and i was unable to change any other items.
### Steps to Reproduce

1. complete a swap
2. when DOT sign transaction screen appears close the box without inputting password or signing transaction

### Your Environment
bXhewYbSzN5LEGRURF5MRVQvUsSPoGNFRYvQF3H98wngtCWdn

**Comment by lolmcshizz** [comment]
When you close the transaction authorisation window, it remains "open" in the extension tabs - you can click on the extension and it'll come up with the same authorisation window. If you click "cancel" that is the only way to actually close the popup fully and therefore abort the transaction. Therefore this is the correct behaviour (without a change to polkadot.js itself)
