### ISSUE TITLE
Changing amount of tokens to transfer after a value has been previously entered not working on first attempt

### ISSUE THREAD

**Issue by dierkness** [galacticcouncil/Basilisk-ui-old#143]
### Description
Once values have been entered in one field, trying to change them doesn't provide the desired values until you change the number a second time.

### Expected Behavior
I expect to change the value of a field and have it reflect the number entered and to change the other token's field as well.

### Actual Behavior
Initial values are entered.
![image](https://user-images.githubusercontent.com/79780142/159537750-3a640336-f644-4e83-938e-e3bb26346dfe.png)

I want to change the DAI field to 1 Dai and have the BSX field update. I highlight the Dai field and press 1. 
![image](https://user-images.githubusercontent.com/79780142/159538026-e49771aa-9183-4310-8a80-0c83ee87bd39.png)
 
Here are the results.
![image](https://user-images.githubusercontent.com/79780142/159538247-24928f37-bc4d-4742-ae2e-ede8134aa8f1.png)

### Steps to Reproduce
1. Enter number of tokens to trade in one of the fields. 
2. Change the number of tokens in the opposing field by highlighting the value and changing it

### Context
You have to enter values twice to get the correct token amounts. Could lead to transactions that are not as intended. 

### Your Environment
Windows 10
Chrome browser

**Comment by lolmcshizz** [comment]
Same as another previously filed bug report
