### ISSUE TITLE
Add percentages/Max toggle and variable percentage slider to swaps U/I

### ISSUE THREAD

**Issue by smtan0x** [galacticcouncil/Basilisk-ui-old#144]
### Detailed Description
Add an option for user to exchange 25%/50%/75%/Max of an asset within the swap U/I. 1% adjustable slider for users looking to trade a more precise amount.

### Context
Adding commonly used percentages to the swap U/I gives a more wholesome user experience. Particularly the 50% option which would be helpful for liquidity providers. A 100% option would allow users to empty their wallet of an undesired asset. Finally an adjustable slider, moving 1% at at time, with updating percentages and values gives users a smoother experience. A vast improvement over manually editing values within the swap U/I.

**Comment by lolmcshizz** [comment]
Feature request already on V0 Testnet feature list to be developed
