### ISSUE TITLE
Graph doesn't update to the appropriate timeframe once the website has been idle

### ISSUE THREAD

**Issue by dierkness** [galacticcouncil/Basilisk-ui-old#155]
### Description
Once the site has become idle and you return to the site, the graph doesn't update to the 24 hour timeframe or allow you to move the cursor to different times on the graph. The percentage change becomes 0%.

### Expected Behavior
Once you return to the web page the graph should update to the previous 24 hour period and the cursor should slide on the graph.

![image](https://user-images.githubusercontent.com/79780142/159793337-20225c13-08e0-4d93-8684-343233ee4d69.png)

### Actual Behavior
The graph doesn't update to the previous 24 hours and the percentage change figure doesn't update.

![image](https://user-images.githubusercontent.com/79780142/159793495-573a62bb-aa3b-48ff-a8b6-b8edba8eca7c.png)

### Steps to Reproduce

1. Leave the site idle. In my case overnight
2. Return to site and try to operate the graph

### Context
Provides inaccurate information

### Your Environment
Windows 10 Pro
Chrome browser

**Comment by maht0rz** [comment]
@Matehoo can you please take a look at this one? should be relatively straight forward. The solution i could think of to implement is to refetch the historical data once the entire dataset (historical + RPC latest) is outdated.

This could mean 'observing' the `dataset` with `useEffect`, and once the latest datapoint (historical or combined?) is outdated by X seconds then refetch the historical data - by updating the `from/to` of the query and calling `refetch()`.

**Comment by Cubo25** [comment]
Browser: Chrome
Version : 53a11f6 
Status : ✅  pass
The graph updates after going back to the trade page after being in idle status or similar actions. 

The graphql request is called and data is updated.
