### ISSUE TITLE
Improve method of choosing assets when making an exchange

### ISSUE THREAD

**Issue by NormandieNiemen** [galacticcouncil/Basilisk-ui-old#177]
### Detailed Description

When a user opens the interface of the decentralized exchange, the default asset exchange path appears, let's say it is bsx:ksm. Let's say the user wants to do the opposite - swap ksm to bsx. For this case, you have a switch button with the class name "asset-switch". However, in my opinion, users usually go the other way - they try to select the desired asset directly (through the drop-down menu for selecting assets to make an exchange), and in this case they will be stuck for some amount of time on your site, since you do not have selecting an asset in the menu that is already in the currently active pair of assets. - when I'm in an exchange path with a bsx:ksm pair, I can't select ksm as the first asset (Pay with).
Recording of process: https://youtu.be/fK5pzsL6g_c

### Possible Implementation

To fix this, simply add the ability to select all assets to the drop-down menu, and display invalid trading paths when trying to such an exchange (for example, exchange ksm for ksm), or automatically, as configured on many decentralized exchanges, if the bsx:ksm pair is currently active, when the user selects ksm as (Pay With), the second asset will automatically become bsx (You get).

**Comment by lolmcshizz** [comment]
Captured in UX Survey
