### ISSUE TITLE
Bug: Broken account selector

### ISSUE THREAD

**Issue by Cubo25** [galacticcouncil/Basilisk-ui-old#184]
The UI is broken for the asset selector

The UI should not be broken for the long name of the account. See screenshot for simple plain explanation

### Expected Behavior
The UI should not be broken in case of long name of the account

### Actual Behavior
The UI is broken -> the snake scrollbar is broken into 2 pieces.

### Possible Fix
The long name should be displayed with few letters or ending with ... in case it is long
![Screenshot 2022-04-12 at 10.13.32.png](https://images.zenhubusercontent.com/61f9263bc6f1d203105662c6/9d694281-2d84-4455-ab6a-61048406a155) 
### Steps to Reproduce

1. Have a vallet with long account name 
2. Go to account selector
3. See the account with the long name in it

### Your Environment
Operating System and version: Mac OS Chrome browser

**Comment by jak-pan** [comment]
I think we can close this when looking at the latest updates.

**Comment by jak-pan** [comment]
Not relevant anymore
