### ISSUE TITLE
Improve: I made swap twice because UI not informing about finishing previous transaction

### ISSUE THREAD

**Issue by nodigyproject** [galacticcouncil/Basilisk-ui-old#187]
### Detailed Description

I didn't see green text (success status hidden very quickly) and made swap twice, because UI did not explicitly inform me that transaction finished and not displayed transaction details

### Context

users will not lose money/tokens

### Possible Implementation

When the transaction finished (the orange status text disappeared) need to show popup window with transaction status and link to the explorer.

![2022-04-13_202548](https://user-images.githubusercontent.com/3663538/163257096-d01ac34c-4852-4730-a535-4275e4ecd2bf.jpg)

https://user-images.githubusercontent.com/3663538/163258720-6921bb58-03ff-489c-b5ee-ee05f7093e01.mp4

**Comment by lolmcshizz** [comment]
Captured through UX survey
