### ISSUE TITLE
Bug: The BSX/DAI pair exchanged more tokens than there were in the wallet. 

### ISSUE THREAD

**Issue by valeriadoma** [galacticcouncil/Basilisk-ui-old#189]
### Description

The BSX/DAI pair exchanged more tokens than there were in the wallet. 
I was able to swap the 5000BSX.  And the transaction was successful. 
How could it be? I received tokens from the faucet in discord one time.
My wallet address (basilisk) bXkYXEt3AiTogzt8UX6JDxg1AxTp4ih5FTRX32fRFV1htFMQw
or (allow use any chain) 5G1p4Eev3CRznCQBdUPVtoM8GueYSyYHNRhHXoKngdBXRpSs

### Actual Behavior

<img width="1280" alt="Снимок экрана 2022-04-13 в 23 19 17" src="https://user-images.githubusercontent.com/102740440/163265535-361936fd-aa48-4e5f-bbcf-9d3809effd3a.png">
<img width="1280" alt="Снимок экрана 2022-04-13 в 23 32 25" src="https://user-images.githubusercontent.com/102740440/163265542-8fb2ecae-9b7c-4a99-b3e0-652cfba56b9b.png">

### Steps to Reproduce

1.
2.
3.

### Your Environment

* Toolchain versions: 
* Version used:
* System type: 
* Operating System and version:
* System specs:

**Comment by Tbaut** [comment]
you had 9.9 Kilo BSX, so this is more than 5000 (e.g 5 kilo)

**Comment by valeriadoma** [comment]
Oh, I'm sorry. I can see it now.
