### ISSUE TITLE
Bug: Various UI overflow

### ISSUE THREAD

**Issue by Tbaut** [galacticcouncil/Basilisk-ui-old#198]
### Description

With an account with large amounts, the UI overflows at various places
### Expected Behavior

It should stay on 1 line for the percentage and not overflow for the token name

### Actual Behavior

![image](https://user-images.githubusercontent.com/33178835/163274120-2a403116-870d-45f8-8fc8-9f69c345162e.png)
![image](https://user-images.githubusercontent.com/33178835/163274037-9a1d59d3-2071-425c-ad1a-edeabc74f7e0.png)

* Operating System and version: Linux Mint, Firefox 99

**Comment by Cubo25** [comment]
Outdated due to new design.

**Comment by Cubo25** [comment]
![image](https://user-images.githubusercontent.com/8873699/185998567-d19848bc-bc55-44a8-8f41-f4e1003f92c8.png)
