### ISSUE TITLE
Bug: ksm - bsx failed transaction

### ISSUE THREAD

**Issue by russian-mussian** [galacticcouncil/Basilisk-ui-old#199]
from **ksm to bsx** transaction **is always failed**. as you see commission is enough.
fix it please.

<img width="818" alt="image" src="https://user-images.githubusercontent.com/83156515/163277080-b5e868f5-8320-43da-b2d3-1a6200163d2e.png">

**Comment by Cubo25** [comment]
@russian-mussian pls can you try it one more time ? we are not able to reproduce it.
