### ISSUE TITLE
Improve -the button for Max.

### ISSUE THREAD

**Issue by fchelium** [galacticcouncil/Basilisk-ui-old#211]
There is no button for the selection of the maximum amount of tokens. 
 MAX

### Detailed Description
 If someone wants to convert all amounts, he has to write by hand correctly to choose all amount. This is not user-friendly.  Please put a button to chose maximum amount. 

### Possible Implementation
 Put a button for the maximum amount

**Comment by winston68** [comment]
I like the button for max, too.
