### ISSUE TITLE
I sent my feedback my polkadot address 5FLWH7UgJ8maTyjjeULa3DW88zbq1FCpvwv1NVjDU6KCVc6u

### ISSUE THREAD

**Issue by Crypto77Hunterz** [galacticcouncil/Basilisk-ui-old#277]
First imppresion the web so smoth i try on my pc so fast i made several transaction it was fast and smooth 
i like design it so nice

 but i have idea add more feature history swap and chart token sometimes not displayed add more token history so we can track a transaction thanks i really enjoy too try it

**Comment by Yayanghasan** [comment]
5Gsxy9JbS77nRHEzf5QKB4ejfnRX2Xmk6ik3YhcRXFQA9VHE
