### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by zapux22** [galacticcouncil/Basilisk-ui-old#295]
Feedback: UI/UX very smooth, auto slippage i like this 👍
Address: bXiW7DTU45pbarQmzsghn36WKwxF4RG9csnfVGgRZyMUM3RgF

**Comment by anonymousproo** [comment]
great project ..... no issue i just feel and swap very easy and smoth
5DekqPNZN9w5f9LQMhHxuG2nbasTwASmQFyzbt3VhvumcU6X
