### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by zapux22** [galacticcouncil/Basilisk-ui-old#315]
Feedback: 
- UI/UX very smooth
- Auto slippage ilike this 👍
- Please Add Stake and Farm 
Address:
-bXiW7DTU45pbarQmzsghn36WKwxF4RG9csnfVGgRZyMUM3RgF

**Comment by Roony89** [comment]
Swapping is slowly apair 

12BQEsZx9WYVkENFrkr7gBE8uk465jRVrXYzmjg5eirPkcA5
