### ISSUE TITLE
Bug: bXhYjRUVv7EVB4QAC2LPhDWf2SxpnYkcmz37j9U4oFHrx4f1x

### ISSUE THREAD

**Issue by Melaa11** [galacticcouncil/Basilisk-ui-old#396]

**Comment by AleCrypto2** [comment]
I don't know if this is a bug or not, or a problem with my network, but after I refresh repeatedly my balance doesn't match like my BSX balance doesn't decrease after successfully swapping to DAI, and DAI balance matches, this is my wallet address bXjttBVmqxhXXogmQqfQpucbAHvEhAGXHAekjRHcwtTFnq2FD others are good, a little input add history, overall the display is still very simple.

**Comment by Melaa11** [comment]
I don't know this is bug, the project its ok
