### ISSUE TITLE
Bug: I can't connect to the wallet 5Dh7sPoXtwsuC7kiHLnC8kcui4RbnBX2mGZ3zu1ArNdcQp2R

### ISSUE THREAD

**Issue by Rzyfp29** [galacticcouncil/Basilisk-ui-old#416]
### Steps to Reproduce

1.
2.
3.

### Your Environment

* Toolchain versions: 
* Version used:
* System type: 
* Operating System and version:
* System specs:

**Comment by dandi0070** [comment]
tolong dong pihak tesnet perbaiki masalah bug di faucet dan konek wallet nya 

bXktpLK3CDfSKQVvucXkHPmrni2tMo2vbfK4PKk57BEqfDthM
