### ISSUE TITLE
Bug: Smooth for transaction already bXkEQKNKqocCA1GfF9GF2DsTfXAq9cxcBmxFFL8gS3KWXf2Ri

### ISSUE THREAD

**Issue by arifbudizz** [galacticcouncil/Basilisk-ui-old#437]
### Possible Implementation

Add liquidity pool and stake features bXkEQKNKqocCA1GfF9GF2DsTfXAq9cxcBmxFFL8gS3KWXf2Ri

**Comment by alwanali22** [comment]
Succesful projects
bXisepYrdojUWHi66FoqdubmJLAJqwgQtx5R4aQzGRpXqUYKP
