### ISSUE TITLE
Improve 

### ISSUE THREAD

**Issue by smarttochoice** [galacticcouncil/Basilisk-ui-old#496]
Displying Asset

### Detailed Description

I have swapped with bXiBZnp7ig8CBHBnLw9o1N9TcVCpKzuN18Cjs5rtCaaB44NR9 wallet, the web interface is user friendly, but I am confused about the assets displayed and have to manually input, there are no % or HALF & MAX

**Comment by Cubo25** [comment]
Duplicate to https://github.com/galacticcouncil/Basilisk-ui/issues/909
