### ISSUE TITLE
[WIP] Trade form

### ISSUE THREAD

**Issue by maht0rz** [galacticcouncil/Basilisk-ui-old#51]
Motivation

Layout
- assetIn
    - AssetBalanceInput
    - Your balance
- asset switcher
- spot price
- assetOut
    - AssetBalanceInput
    - Your balance
- TradeInfo
    - trade fee
        - absolute value (e.g. 123 USDC)
        - percentual value (e.g. 0.2% or 20%)
    - slippage
        - absolute amount (e.g. 123 USDC)
        - percentual value (e.g. 0.2% or 20%)
    - trade limit (maxSold / maxBought)
        - absolute value (e.g. 123 USDC)
        - (!) this is calculated from the spot price + allowed slippage 
    - errors / info
- TradeSettings
    - allowed slippage (default 0.5% for XYK, for LBP TBD calculate based on fee)
        - allowed slippage can work even if 0%, but only in a specific case
        - validation for > 3% or in case of LBP > 5% (should be discouraged)

Error states
- info/warning (info error states are errors that are non intrusive, but still disable the trade button)
    - No active account
    - lbp repay fee is applied
    - sale ended
    - sale not started yet

- errors
    - max limit (this covers the pool too small / trade too big case as well / preemptively)
        - use protocol constants for the max limit(s)
    - min trade limit (should include existential deposit + differentiate between buy/sell)
        - assetIn should show a warning in a case where the left over balance is < existential deposit
        - assetOut should show a blocking error in a case where the after trade balance is < existential deposit
    - not enough asset balance (show which asset balance isnt sufficient)
        - this only cover assetInBalance/assetOutBalance and does not cover any tx fee logic
        - trade fee might be embeded in the assetInBalance/assetOutBalance
    - slippage higher than allowed slippage
    - pool does not exist / invalid pair (this has to do with clearing of assets when selecting in/out assets)

Notes
- Fee is added to the calculated amount
    - if calculateOutGivenIn, then the trade fee is paid in assetOut, and the form should show the calculated out amount + fee. This means that the validation for insufficient balance will be triggered including the fee as well and the user should not run into a case where his balance was not able to cover the trade transaction.
- If the transaction payment asset is the assetIn, then the insufficient balance error should take the transaction fee into account as well.
- Insufficient balance for paying the tx fee is a standalone error, where the balance is compared to assetInBalanceAfterTrade + fee payment asset balance.
- TODO: extract repay fee logic from code

Detailed description
1. Initial state (on load with no query params provided)
- assetIn is preselected as BSX (0) and assetOut is undefined
- initial unit is none / undefined
    - In a case when there is no activeAccount, show 'connect account' as an action button
    - In a case when there is an activeAccount, show 'trade' as an action button (disabled + validation above)
        - this invalid asset selection is handled as 'info' not as a validation error visually
- trade fee & slippage will be '-' (none)
    - trade fee / slippage will take the same space as errors / trade info (this is a design task)
- spot price will also be empty, since it can't be calculated yet (-)
    - trade settings
        - allowed slippage is `0.5%` with auto pre-fill
    - 'your balance' is hidden for assets that are not selected (e.g. assetOut)
        - when the opposite asset isnt selected (not a valid trade yet), then you can only see your current balance, but no after trade balance / change indicator

**Comment by mckrava** [comment]
`- this invalid asset selection is handled as 'info' not as a validation error visually` - I guess we can avoid invalid asset selection by providing only valid combinations of assets for select. I mean if `assetA === BSX` so `assetB` select must contain only that assets which can be traded with BSX. We need just look to available pools with BSX asset.
