### ISSUE TITLE
Add Button Max

### ISSUE THREAD

**Issue by rawimoforever** [galacticcouncil/Basilisk-ui-old#515]
Maybe you can add a max button to speed up the swap process if the perpetrator wants to swap all the tokens owned 

My Address : 5GVrbn2a7dEHeMhit95g4ruYD83f5XdSKuKMuPm4w2bM21F9
BSX Address : 
bXm2ZnRQpntbys3S1mkzQ8jZatgDBMFAQQu97QFrXjR7hqWj7

**Comment by rahmatwiratmoko** [comment]
Thanks sir 🙏

**Comment by rawimoforever** [comment]
Goto moon sir 👍🏻🚀
