### ISSUE TITLE
Add 

### ISSUE THREAD

**Issue by bnr667** [galacticcouncil/Basilisk-ui-old#522]
Consider Light Mode, Balance Percentage Bar, and Mobile web version user interface

### Detailed Description
 I guess we need a light mode, coz some people feel uncomfortable with dark mode. 
The balance percentage bar to help people execute transaction easier.
The current UI is not friendly to mobile web version user.

### Context

 user Will be more comfortable.

bXmXSY4VgSxDm8vxbSb8auY5VDzgt6NA2QvpwDXHHz3grjMYC

**Comment by Lawflo** [comment]
Change amount of swap and
Thanks for giving us such a great opportunity. I am supporting it. always success for the development team to the moon
15GZyGEehiG5TSjcodHSuaF1aE7upZuzKerz556YhsRfsNTJ
