### ISSUE TITLE
No any bug, smoothly use. 

### ISSUE THREAD

**Issue by Rijulove** [galacticcouncil/Basilisk-ui-old#539]
### Steps to Reproduce

1.
2.
3.

### Your Environment

* Toolchain versions: 
* Version used:
* System type: 
* Operating System and version:
* System specs:

**Comment by septian-bery** [comment]
1mmkaXYAMJf3Gf4nurr7Gn69aP56vBrGr9HaQdfs1ap9pcV

Fast transaction

**Comment by septian-bery** [comment]
Fast
