### ISSUE TITLE
Add fetching of locked balances by lockId and address

### ISSUE THREAD

**Issue by maht0rz** [galacticcouncil/Basilisk-ui-old#57]
We need to add fetching of locked balances due to how the LBP `repayTarget` works, and how vesting is implemented.

Knowing what the locked balance of a given address is, is detrimental to figuring out e.g. which LBP fee should be applied.

### Detailed Description
Locked balances exist in two palettes, both `balances` and `tokens`. Where `balances` will include locks for the native asset, and `tokens` will include locks for 3rd party assets. Each lock is identified by a `lockId` which can be used to determine the purpose/reason of the balance lock.

### Possible Implementation

Example query:
```graphql
query GetLockedBalanceById($address: String!, $lockId: String) {
    lockedBalance(address: $address, lockId: $lockId) {
        id,
        amount
    }
}
```

Native asset locks can be fetched as follows:
`balances.locks(accountId)`

Balances for non-native assets can be fetched as follows:
`tokens.accounts(accountId)`

#### Handling of `lockId`

Since the node storage does not offer filtering by ID, we have to filter for the correct `lockId` on the client side, by filtering out the unwated lock entries for both native and non native assets. The resolver should only return the lock which matches the requested `lockId`. If locks for both assets are present and match the given `lockId`, the native asset lock takes precedence.

> Ignoring one of the locks in a case there are multiple locks for the given `lockId` is not an ideal solution, but to date we don't have a feature which would create a lock for both assets using the same `lockId`. This can change in the future.

**Comment by dexterslabor** [comment]
As a note two assets can have the same lockId

![Screenshot 2022-02-16 at 13.01.49.png](https://images.zenhubusercontent.com/6188fb3dad80f64d846cbf9e/bd46a7f3-8916-4b22-a4af-ca506c5e1702)

**Comment by dexterslabor** [comment]
The spec was clear on:

> If locks for both assets are present and match the given lockId, the native asset lock takes precedence.

I was not sure what to do if there is one `lockId` for multiple assets that are non-native. The following from the spec was contradicting one instance I was able to create (see screenshot above), where the same `lockId` is used for 2 different non-native assets. 

> to date we don't have a feature which would create a lock for both assets using the same lockId

The current implementation follows the following behaviour:

> If locks for native and non native assets are present and match the given lockId, the native asset lock takes precedence and non native assets are not returned. If lockId is not present for native asset, but for multiple non native assets, than multiple locked balances with the same lockId are returned.

**Comment by dexterslabor** [comment]
Another way the implementation differs from spec is that `address` is optional in the query parameters. In case it is not present, it takes`id` from parent entity. 

```
export type QueryLockedBalancesArgs = {
  address?: InputMaybe<Scalars['String']>;
  lockId: Scalars['String'];
};
```
