### ISSUE TITLE
Transaction History

### ISSUE THREAD

**Issue by antlc** [galacticcouncil/Basilisk-ui-old#600]
### Detailed Description

It would be good to feature a page displaying transaction history and pending transaction. When my transaction is processing and I refreshed the page, currently there is no way for me to check transaction status on the site. 

My BSX Address:
bXmtXSFDtPKzay4oaNc4xwd5qx6rYurdnQuq4KiqxBfSYtsha
Substrate Address:
5HMpFbqdi4ctkP5HUzAEskRoGYh2e96pKv1JprkVPGvC5iQd

**Comment by afanrestu** [comment]
good one
