### ISSUE TITLE
Bug Swap

### ISSUE THREAD

**Issue by aryarriady** [galacticcouncil/Basilisk-ui-old#633]
I have swaped bsx to ksm, its succed but my balance didnt decrease
address : bXj1i2GSkooRnh9KUs4HBqvKWyfLXF2fvapDaf8FB1yaTDrTN

**Comment by dinasopi** [comment]
sometimes the swap is successful but the token is not reduced  

bXhHh4MemCwTArHaPsjbvgvT1bAXY3HCiN9u4R5HH9VqaAvNV

**Comment by gans888** [comment]
sometimes the swap balance doesn't change and old transactions               



bXh7H8QLXt91...AwJwv88b2Um8

**Comment by gans888** [comment]
sometimes the swap balance doesn't change and old transactions

bXh7H8QLXt911qw9ZGgwL2MRLfaKii56mjJsPAwJwv88b2Um8
