### ISSUE TITLE
Add Some Features. 

### ISSUE THREAD

**Issue by Ngikngok666** [galacticcouncil/Basilisk-ui-old#639]
Adding some Features

    ---Graph Chart 📈📊 : 
 
    Added candle stick feature in the graph chart section. Don't just be straight like that because it looks boring and too monotonous for some users including me. So that users knows the original price of the token itself. Users can also find out how the price from some time ago was good or not. 

   ---Account Section Features : 

   As well as the addition of an explorer on the Basilisk network. It allows the user to browse and view the transactions that the user has recently made.

Address : bXmDECWWgY7oWcsSRguX7UBw3oyhwWwVjU2Z5oA2HxZvWVY2t

![Screenshot_2022-04-18-09-04-13-862_com kiwibrowser browser](https://user-images.githubusercontent.com/95911237/163744660-c972b2c6-48f3-4ab3-8cf4-44c5c6579c8f.jpg)

![Screenshot_2022-04-18-09-04-06-511_com kiwibrowser browser](https://user-images.githubusercontent.com/95911237/163744662-3cb3feaf-06d1-4bad-ab63-46e14041371c.jpg)

**Comment by indodax88** [comment]
make it simple about size token, not useful for my opinion
address:bXjxEKD28y6ej5nLSxabDdoM8c7w76bKGA6afDwhhExnjZu7a
![simple](https://user-images.githubusercontent.com/103088272/163750587-eacfb087-e2ac-4bd3-a923-e016b3f648b9.png)
