### ISSUE TITLE
Add global error handling for Apollo queries and mutations

### ISSUE THREAD

**Issue by maht0rz** [galacticcouncil/Basilisk-ui-old#66]
For the sake of not having to handle errors per query or per mutation, we need a global way to identify and respond to errors that happen within apollo.

### Possible Implementation
One of the possibilities how to approach this issue is using the built-in error handling links such as [this one](https://www.apollographql.com/docs/react/api/link/apollo-link-error/). I (Matej) was unable to get this error handling to work. 

Alternative to the link above, would be to wrap every `useQuery/useLazyQuery` or `useMutation` into a custom hook that will handle the returned apollo errors in an unified manner.

Right now, handling the errors would mean just logging them with `log.error(...)`.

**Comment by janfabian** [comment]
I confirm the Apollo Error Link is not working for locally managed resolvers. I assume, that Apollo Links  in general are only triggered when the client communicates with Graphql server. Since all resolvers are local, I'd say the links are skipped.
