### ISSUE TITLE
Bug: Chart not showing

### ISSUE THREAD

**Issue by steffanomcrey** [galacticcouncil/Basilisk-ui-old#674]
char on the web doesn't show the latest price chart and can't copy the address on the web, the balance showing is not right I have 10 tokens but on the web it says 9999 tokens

bXmtYU5wKynZQYZM6efJwEmZk511Co9DAbFY7tAe9dBQKHEqX

**Comment by SergeyZver** [comment]
Hi! I am not displaying the price chart.  https://prnt.sc/D-_uFxtn059Z

bXmZv8t59x6rvsCN9q5hYxdbFvXQ5UEEcLNZrNFq9GuZ9Jndr

**Comment by nomz11** [comment]
hi , chart not showing in my display

bXgxgZFfFAgCrHXdDuMWbtcD6v48E3jR1Hmsocdmgdu9fgH9r
