### ISSUE TITLE
No everything is ok 

### ISSUE THREAD

**Issue by shakilbd69** [galacticcouncil/Basilisk-ui-old#678]
### Expected status

No everything is ok 5HVtHUAu8tYP5RBrL9PBR3ynQ5g3vYm1uRuv3xrZajQGbEzP

**Comment by mohit2200** [comment]
Everything Works Fine For Me Thanks You 🙏

bXhqBbv2CtgpnFf2BMDS8fMWYnt9SLV9Vv5hGqCun4FobAQtv
