### ISSUE TITLE
Improve 

### ISSUE THREAD

**Issue by nurulnur** [galacticcouncil/Basilisk-ui-old#688]
Network to slow

### Detailed Description
The network is still slow, the balance is slow to appear and the swab is too, and there is no notification if the transaction is successful.

### Context
![image](https://user-images.githubusercontent.com/79836409/163776406-db81b2b0-3735-4376-9c72-1d0a53542896.png)

### Possible Implementation
Maybe it can be accelerated even though using blockchain

### My address
bXjmmKj6KgHoK1KciqGMeEXHndtYgTpePZqGHVFb62BCQaWic

**Comment by jaykhubani777** [comment]
Everything Is Fine Sir But Website Working Little Slow Please fix it 🙏

bXkVd4bkDyZxNzbnLDB7nUJoRDFXXN72CQvExpmokuf2AyZ3c

![Screenshot_2022-04-18-13-40-47-77_796fe9d23d8d59ff5360ab8ee32f2fda](https://user-images.githubusercontent.com/103926042/163778299-d227e9e6-9deb-41aa-a10d-ab5c4ad16977.jpg)
