### ISSUE TITLE
more functions

### ISSUE THREAD

**Issue by juliosilva2374** [galacticcouncil/Basilisk-ui-old#750]
all good, good project, if they could put more functions like betting or opening positions it would be good.
bXjE56tGjRdUXGyEXMtLm9aVHoAc4vbZAkPYAd5KQW67m5CU8

**Comment by Zobasky** [comment]
More functions needed 
5HpnKHmcRRAC3UQjDRYKit53htg7LxX1SesEyAMqqzWE14XM
