### ISSUE TITLE
Improve 

### ISSUE THREAD

**Issue by ZHOGIA** [galacticcouncil/Basilisk-ui-old#759]
The testnet runs well and smoothly, I didn't find any bugs at all, this is just my personal opinion, the rest is very good transaction is also fast.

My address: bXn2FLxfF5LzuKAVNuupgQMRiSpwbSXDpzQKfqgwZKeJyJSsQ

**Comment by Lipika40744074** [comment]
Transactions all ok but I request please swap option add Max and half 

5G6Famth92vJ33JdafZBYcvicFteTMfN2ddoqTtpqPfSK1w4

**Comment by Lipika40744074** [comment]
Very good project add swap Max and half add stake and farm 5G6Famth92vJ33JdafZBYcvicFteTMfN2ddoqTtpqPfSK1w4
