### ISSUE TITLE
Bug: unbalanced balance and no transaction history appears

### ISSUE THREAD

**Issue by Adiwijaya5656** [galacticcouncil/Basilisk-ui-old#780]
The transaction speed is good, but sometimes you can't copy the address or make an error, so newbies are sometimes confused
and please show the transaction history on this project so we can see our transaction trajectory, and there is a bug that our token balance doesn't balance, is this a UI problem or what so please fix it 

my wallet : bXhTQBNRZMgi1YiDBpyfEXefSSkNyEEJ7vZG7SuFMCp2S56RG

**Comment by dalidali456** [comment]
是的
