### ISSUE TITLE
Bug: i didn't find any bugs

### ISSUE THREAD

**Issue by slicelif** [galacticcouncil/Basilisk-ui-old#786]
### Description
 no bugs, I want to give feedback about my experience when trying this website

### Context
i have tried this testnet, i have done several swaps. bsx to dai token, bsx to ksm token, bsx to ausd token, and vice versa. smooth web, no bugs occur
this is my wallet address: bXiYc44rPeifx6EZnVLEt4qLcgwHNk4BPJvVnz71US2y1Rok6

**Comment by nomz11** [comment]
i didn't find any bugs
