### ISSUE TITLE
I have experienced trying to use this web test

### ISSUE THREAD

**Issue by bangindraa** [galacticcouncil/Basilisk-ui-old#803]
### Description
I have tried this testnet, namely by swapping bsx to dai tokens, bsx to ausd tokens, bsx to ksm tokens and vice versa. web test works smoothly without any problems
this my bsx wallet: bXmYQ1VeU6eJ4A6GydCggmdxtFhuv6ozuzFC2eNvvSN8Z3Mmt

**Comment by bangindraa** [comment]
Hai

**Comment by mamunptsc** [comment]
Very good polkadot swap
Bsx/Dai, bsx/ausdt 
Is very good working
5out of 5

My address: bXhzsFmG6bsi19Qosyj5QNhZEL6mrUZWcPQY7RgoeHBG4c5kW

**Comment by Metallfunky** [comment]
I believe this is a faithful project.The projector has a lot of attractions so hopefully the project will be better in the future and will be the best. , i have try testnet is very smoth , good UI/UX
I love it  great job team 

my address bXj5riFB1B4X87heqs3JGovWHow1cZPrFDXK5w876jof3uyhU
