### ISSUE TITLE
i'm done using this testnet

### ISSUE THREAD

**Issue by ikyysulaiman** [galacticcouncil/Basilisk-ui-old#804]
I have tried this testnet, web test works smoothly without any problems
my bsx wallet: bXjdevW49xAdwpBZRPXRdtneNPBgntK4ZLu3G5BMzmyEqVULK

**Comment by mamunptsc** [comment]
Wow i I am exciting. New testnet very good polkadot

My bsx address: bXhzsFmG6bsi19Qosyj5QNhZEL6mrUZWcPQY7RgoeHBG4c5kW

**Comment by yunanh42** [comment]
I've used it and currently I'm not having any problems when swapping

my address : 15fnmateY4Lkjnph5yhiZC5nHctGinozy7AJeYLXCpZHSW9A

**Comment by MKLNKs** [comment]
Hey
I finished testing.. I did this for a month
My wallet BSX bXhN11Y3F9UKxKR9j3HruWkJHPxMzA2r5jUp8zV3T5k9EmQ4b
