### ISSUE TITLE
After swapping it shows transaction pending for a long time and my balance doesn't update after swapping as well with no way to keep track of my transaction history.  5DXM9PhtUb3CRfsNh3c1KemsKyUE3d7VDUUWgPsckGTsou9x Bug: 

### ISSUE THREAD

**Issue by HDCHACHO** [galacticcouncil/Basilisk-ui-old#805]
### Steps to Reproduce

1.
2.
3.

### Your Environment

* Toolchain versions: 
* Version used:
* System type: 
* Operating System and version:
* System specs:

**Comment by HDCHACHO** [comment]
After swapping it shows transaction pending for a long time and my balance doesn't update after swapping as well with no way to keep track of my transaction history.  5DXM9PhtUb3CRfsNh3c1KemsKyUE3d7VDUUWgPsckGTsou9x

**Comment by mamunptsc** [comment]
All ok but pending time to long. Plz fst this pending time almost over all ok.. good performance

My address: bXmAXpUN88v6A8wirwFGcKtPpbbrtodhjuztTstBqgiFx1oft
