### ISSUE TITLE
Add fetching of the last relaychain and parachain blocks

### ISSUE THREAD

**Issue by maht0rz** [galacticcouncil/Basilisk-ui-old#81]
Add fetching of the last relaychain/parachain blocks for the purposes of the LBP trade page - We need to know the relay chain block in order to do some calculations (e.g. current weights, current spot price).

### Detailed description
The `LastBlock` entity (described below) does not have a data resolver directly, but it is populated/pushed to the cache manually instead (implemented separately). This enables us to utilise a subscription, instead of fetching those information on a per-query request basis.

This task only deals with the actual fetching of the parachain/relaychain block numbers. Pushing to the cache is a separate task.

### Possible Implementation

Example query:
```graphql
type LastBlock {
    parachain: String!,
    relaychain: String!
}

query GetLastBlock {
    lastBlock @client {
        parachain,
        relaychain
    }
}
```

The parachain block should be subscribed to via `api.derive.chain.subscribeNewBlocks(...)`.

With each update (subscription triggered), the `relaychain` block number should be refetched for the specific block hash (link below) we've received via the subscription. The relaychain block number can be fetched using `api.query.parachainSystem.validationData()` (stored as `relayParentNumber`).

You can read the storage at a specific block hash, as shown in this [example](https://polkadot.js.org/docs/api/examples/promise/read-storage-at).

Both parachain/relaychain blocknumbers should be pushed to the cache respectively.

**Comment by Cubo25** [comment]
Closing due to clean up.
