### ISSUE TITLE
Bug: hello sir I want to report that in an swapp transaction. I didn't find a failure and it was very smooth .my addres: 5FWuCaijs7dfav4yyQ9PutwHnt4mtHcmMjXzCkGbNDHmFeRQ 

### ISSUE THREAD

**Issue by Aprtzy99** [galacticcouncil/Basilisk-ui-old#817]
### Steps to Reproduce

1.
2.
3.

### Your Environment

* Toolchain versions: 
* Version used:
* System type: 
* Operating System and version:
* System specs:

**Comment by RamdanSe55** [comment]
"bXi3X3PK2nqPDYzuqcTkS9XikEfCDAAc2hHEveaTFBVdtTpCT"
slow transactions kinda bored to user who always had no time to wait maybe we could make it better, also need more features even though it's only testnet and change its interfaces to more friendly, and add button balance so we can see what we've been swapping so we don't have to keep it in our mind. but I think this project will be great if those are much changes
