### ISSUE TITLE
Add refetching of time-sensitive data after the last block changes

### ISSUE THREAD

**Issue by maht0rz** [galacticcouncil/Basilisk-ui-old#82]
In order to maintain fresh data on the client side, we need to invalidate the cache and refetch certain queries. 

### Detailed Description
Certain queries, such as getting the LBP pool by assetIds need to be invalidated & refetched with each new last block (parachain+relaychain). This can be achieved using Apollo's `refetchQueries`, you can read more [here](https://www.apollographql.com/docs/react/data/refetching/#clientrefetchqueries).

### Possible Implementation
If you want to 'subscribe' to be refetched as a query, you must include the following:

```graphql
// example query
query GetLBPPoolByAssetIds {
    lastBlock @client {
        parachain
    }
    ...
}
```

By requesting the `lastBlock` data in our query, we've created a coupling which can be used in conjunction with `.refetchQueries + updateCache` to refetch the given query.

Fetching of the `lastBlock` data is implemented separately in #81. In order to trigger the aforementioned refetching, we must do the following:

```typescript
// pseudo code

client.refetchQueries({
    updateCache(cache) {
        // save last block to cache, it will trigger refetch of our interested queries
    }
})
```

By running our cache update inside `refetchQueries + updateCache`, apollo will automatically refetch all queries that rely on the `lastBlock` data. We also have to handle the case where we populate the `lastBlock` for the first time, since we don't want all the queries to refetch right away when we get our first `lastBlock` data from the chain.

**Comment by Cubo25** [comment]
Closing due to clean up.
