### ISSUE TITLE
Handle runtime upgrade

### ISSUE THREAD

**Issue by mrq1911** [galacticcouncil/Basilisk-ui-old#83]
In the case of a runtime upgrade, we have to make sure that constants and metadata are loaded again. The simplest solution is probably to just force the client to reload the whole app.

There is an example of how the runtime upgrade is detected in the test, it is not the most sophisticated solution, but it is a function starting point. Could be improved upon by hooking directly to the polkadot.js SDK which also already can handle upgrades.

https://github.com/galacticcouncil/Basilisk-node/blob/master/scripts/upgrade-runtime/index.js#L78

> Detection of the `parachainSystem.ValidationFunctionApplied` basically triggers a process where with every new block we're checking whenever or not you can already connect to the RPC node with the new spec version. 

Probably interaction with the app should be probably paused from the moment upgrade event is detected and allowed again with the refreshed state when is possible to use new spec version on node again.

**Comment by Cubo25** [comment]
Closing due to clean up.
