### ISSUE TITLE
Add 

### ISSUE THREAD

**Issue by zoronesia** [galacticcouncil/Basilisk-ui-old#830]
### Possible Implementation

5C5cqM7SGiKQKnHGdYwi98BHsUE2QxNbbzvtU9Ky8cB8YwSH

+ add max/half button when swapping token
+ add view in explorer after swapping token

**Comment by Statesmanakp** [comment]
5FbdAAvDXG6Ua9meiKgSNhbPaGrb1gmdosTmQSjhp9Mi8jqN


Value of remaining balance not easy to understand 

swap is slow
