### ISSUE TITLE
Bug: Balance display is wrong.

### ISSUE THREAD

**Issue by mameron** [galacticcouncil/Basilisk-ui-old#835]
### Description
 The interface was good because it was simple and intuitive, but there was a problem with the balance display. Also, I think a slider button is necessary to improve operability.

My Wallet:
bXkwnoe9kc62q9MiN3efXQCqRBqH4rXTSBgWAqEX16p5iqBB1

**Comment by antoioramdani** [comment]
![Screenshot_20220420_185633](https://user-images.githubusercontent.com/103843289/164229434-56c26533-daff-4b46-9127-5113c3819a23.jpg)
Done all
Bug balance

it is stated that everything is smooth swap bsx to ksm
bXmPpioyHWqDcven7p5qqjH2jumfdM3nVdcUMksu83QtV9anM

**Comment by rapha4u** [comment]
hello, i tested the swap functions and the speed is very slow, and also the balance shows incorrect value after swap and lastly the unit/size (tera, mega, giga, kilo, deci, centi, mili, micro, nano, pico) is so unneccesary and causes confusion, here is my wallet address 5FZ1qerMJLMAsjj8HWg7HEKsAvZ3R2kWD876iLr2MwgJS4nH
