### ISSUE TITLE
Bug: No Bug All Is so good

### ISSUE THREAD

**Issue by mahfuz1245** [galacticcouncil/Basilisk-ui-old#838]
There i don’t get any bug.The testnet is so speedy and smooth.I eagerly wait for Mainnet.

I test Basilisk(BSX) testnet using my polkadot address:
15MsaD9GDq33Jq92TNGmmDgRp5RtS4jDZZdu6ZywWJj19K64

**Comment by antoioramdani** [comment]
No bug
it is stated that everything is smooth swap bsx to ksm
bXmPpioyHWqDcven7p5qqjH2jumfdM3nVdcUMksu83QtV9anM
