### ISSUE TITLE
Basilisk

### ISSUE THREAD

**Issue by abys6** [galacticcouncil/Basilisk-ui-old#840]
No bug all good, although I wasn't able to swap through some tokens, I tried it didn't go through

Bifrost address: dHQcQpgEhgfBqHgjMKaaTLvCnyaFCuzoybN4uyYDx1Troxp

**Comment by antoioramdani** [comment]
No bug
it is stated that everything is smooth swap bsx to ksm
bXmPpioyHWqDcven7p5qqjH2jumfdM3nVdcUMksu83QtV9anM
