### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by alextiger22** [galacticcouncil/Basilisk-ui-old#850]
no bug ITS good and fee low great

bXn2dJPRFastrPshXC8tBMmAuFnYrS3AAFiBvMrX8NWfrdFf7

awesome

**Comment by Secondbornloyal1** [comment]
So far so good. The bug I noticed was that the BSX amount doesn't really reduce even with the multiple swaps.  Regardless the dex Is really easy and smooth to navigate.

My wallet address:

5FFYdKAatC8st3pQGbAhkeb8R1KpkdZcKX1AbnPJiyRMwR8f
