### ISSUE TITLE
Add 

### ISSUE THREAD

**Issue by betarbi** [galacticcouncil/Basilisk-ui-old#867]
Need to add more features like future trading, farming, crosschain bridge. Like Dot to bsx.

bXm5qguGNWyTPZZtkE9xToYSfS7LNL1Eptjos9G777FNfYjht

**Comment by Pritam6304** [comment]
It would have been better to add the liquidity option

My address : bXmZwo7SterPdsrGR2RY1SUNEvsCYwSaMfk3DwSH7X71PiHim
Address : 5H3EcU4dyb1wfAY88odHNbiCFK32fj3PakDUSaBeiiV2u5UU
