### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bangpateng** [galacticcouncil/Basilisk-ui-old#907]
Done All Transcaction

14GDJAH9CG9swaapdXE8xubSa7ksmZnPMkhyMsc9Yz8N56ag

**Comment by erik-26** [comment]
transaction is fast i think
and faucet is work 
i think next update more feature again 
more token for next update
thank you 

bXkzycbRQKt4Yt8Vvtn764DKPaH4Qg62YvbT4wUPkkrTxfzUu

**Comment by Ars1795** [comment]
![Screenshot_2022-04-24-16-05-04-583_com kiwibrowser browser](https://user-images.githubusercontent.com/104300277/164970041-596b486e-0be6-437a-82e4-3b6ac455698a.jpg)

I've tried the features or menus on the Basilisk website. That is doing the exchange as much as 5 times. Everything worked.

My Addeess : bXgvku5122wjtVtj22E5Y6pfyhe7jS2EqESLH8CTqDfnd4y9B

**Comment by kopralosd43** [comment]
so far i tried, i can't found a bug 
My basilic addresss
bXghvZ9Kh1RMJD3FQpopq8P8CXfvs8nfKUWjXYcF9qmPrteiS

![IMG_20220425_221051](https://user-images.githubusercontent.com/104373595/165118437-06b1e6b9-a473-407a-8b9a-b8ea323ca029.jpg)
