### ISSUE TITLE
Link to Onchain Transaction Completed(Success or Failed) 

### ISSUE THREAD

**Issue by ajeek** [galacticcouncil/Basilisk-ui-old#913]
### Detailed Description

While the Swap display SUCCESS, no link can be clicked in order to see the on-chain transactions
### Context

Users will be able to view the transaction onchain for either Success or Failed so as to get the transaction ID for follow up
### Possible Implementation
A pop up link

**Comment by lolmcshizz** [comment]
This is on our list of additional features for later iterations of the testnet
