### ISSUE TITLE
Bug: Can't enter a number with a decimal separator ( , )

### ISSUE THREAD

**Issue by imaxsvel** [galacticcouncil/Basilisk-ui-old#928]
**Environment:** 
- URL: https://testnet-app.bsx.fi
- Version: b9bd747
- Account: bXhC6fen2x6AaNJZ966Qj8dNTnL2rG5hN7JubnbbnoJPQ8CJu

**Preconditions:** 
- Account logged
- Chosed exchange DAI - BSX

**Steps to reproduce:**
1. In DAI value input insert "10";
2. In DAI value input add "," .

❌ **Actual Result:** In DAI input = "10".

✅ **Expected Result:** In DAI input = "10." .

**Comment by Cubo25** [comment]
#927 #926 These issue are the same
