### ISSUE TITLE
Bug: Insufficient Balance Error Message [max button]

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/Basilisk-ui-old#930]
When I click the [MAX] button to swap all of my DAI to BSX, I get "insufficient balance" error.
### Description

I would expect to be able to click [MAX] and then be able to execute the transaction to swap 100% of the balance of the token in question
### Expected Behavior

Should be able to complete the transaction without the "insufficient balance" error message blocking it
### Actual Behavior

As per screenshot below:
<img width="756" alt="image" src="https://user-images.githubusercontent.com/97540577/165723441-9927c421-edf5-4ef5-8de0-c1cdec9d00c4.png">

### Possible Fix

Sers you are shadowy super coders, you can work it out
### Steps to Reproduce

1. Choose Asset 1 as DAI
2. Choose Asset 2 as BSX
3. Press [MAX]

### Your Environment

* Toolchain versions: 
* Version used:
* System type: 
* Operating System and version:
* System specs:

**Comment by Cubo25** [comment]
@lolmcshizz I cannot reproduce this on any environment.
