### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by milyaaa1998** [galacticcouncil/Basilisk-ui-old#943]
During the test of the program, as such, no errors were found. I want to praise the developers for such a convenient application and project interface. Rating 10 out of 10. I hope for the future development of this project. No errors found..

**Comment by milyaaa1998** [comment]
5CJmNP2vxqSjFod7jVyH64e5ULA9JrHhXypmWPw62HSnMLuS

**Comment by jak-pan** [comment]
Thank you but please don't open issues for this. We need to look at them and close them which costs us time.
