### ISSUE TITLE
Testnet Basilisk

### ISSUE THREAD

**Issue by danFauzan** [galacticcouncil/Basilisk-ui-old#945]
![Screenshot_20220501-101534_mrJennn~2](https://user-images.githubusercontent.com/77300125/166130895-bfec1d3e-dbf8-41ef-9487-cf61030c56e6.png)
![Screenshot_20220501-100420_mrJennn](https://user-images.githubusercontent.com/77300125/166130896-13851eb7-1f36-4fde-9759-2be8508713a5.jpg)
![Screenshot_20220501-100302_mrJennn](https://user-images.githubusercontent.com/77300125/166130897-dab23e55-b7d8-4247-b81a-4a93695ab9dc.jpg)
![Screenshot_20220501-100527_mrJennn](https://user-images.githubusercontent.com/77300125/166130898-33be5f66-3564-48b2-8cbf-04232150d11c.jpg)
![Screenshot_20220501-101031_mrJennn](https://user-images.githubusercontent.com/77300125/166130899-d8b09924-bb76-4533-baa7-81e6d731d2b2.jpg)
![Screenshot_20220501-101627_mrJennn](https://user-images.githubusercontent.com/77300125/166130901-a7b45c77-23d4-43ac-9baa-50c398b8d938.png)
![Screenshot_20220501-100605_mrJennn](https://user-images.githubusercontent.com/77300125/166130902-db2fa2a0-0142-476f-8227-f7df14263c05.jpg)

Thank you so much for allowing us to utilise the basilisk testnet; we are extremely pleased because it appears that we will be able to learn trading quickly. All transactions are certified successful in the basilisk testnet , use 0.1 , 1 , 3 slippage succes , just some token can't swap . It's incredible; I found no bugs or issues, no missing words or sentences, and no misspelt letters in the entire testnet. I hope the project continued success and speedy growth.

My wallet address 
bXiL8QWLae9SKt5uG7pbfkDrQEoQi4FsAmqkfrLCc8BwH6ZtT

My discord : ahmadfauzan#2080

**Comment by MonoAmumu** [comment]
![image](https://user-images.githubusercontent.com/56051943/166861059-890b8115-c714-408e-9041-c29d5aa99565.png)


It's a different way of swapping, a unique way, I like unique things. Basilisk has something different!

**Comment by jak-pan** [comment]
Thanks but please don't open issues for this. We need to look at them and close them which costs us time.
