### ISSUE TITLE
Bug: balance error

### ISSUE THREAD

**Issue by wmahendra1994** [galacticcouncil/Basilisk-ui-old#950]
I found a bug, which I think is very critical.. 1. there I have a balance of 9.97 BSX, then I try to swap 10 BSX and you can see the transaction is successful, please fix it. 2. The slippage is set automatically (3), but when I change it to 0.5, 1, even 5.. the resulting calculation doesn't change, the same as the slippage setting (3
![IMG_20220503_011427](https://user-images.githubusercontent.com/104789820/166303535-7787499d-6ad0-42aa-9cde-c2ef0ef53f1b.jpg)
). 

my address : bXmuLmKmaiPiec1bLbx5MJJgySEt3Pr6svb8dYKJPD5upmEQu

**Comment by Cubo25** [comment]
1. Problem is that your balance was 9.97 Kilo that means 9970 so when you did 10 BSX transaction its completely ok.
(Whole unites functionality has been scraped)
2. Transaction was successful that comes from the point 1.
3. The slippage problem cannot be reproduced.

Please visit our production https://app.basilisk.cloud/#/wallet and try out all your issues if you are sure they are still persisting.
