### ISSUE TITLE
Basilisk testnet feedback

### ISSUE THREAD

**Issue by Neilous** [galacticcouncil/Basilisk-ui-old#952]
First of all, I want to thank the Basilisk project team for the opportunity to test their product, because for me, as a novice user of WEB 3 technology platforms, it is very important that the functionality provided is simple and intuitive. The testnet was completed in full, the transactions were successful, no bugs were found.  As a wish, I will add that it would be convenient to add some timeframes on the asset chart for a complete price picture, and it would also be convenient and less time-consuming if, when hovering the cursor over the wallet balance, you could select and view the balance of other assets.

12TjMB1j7Qns2BbaQDfiNeghk2C36GcBnFwBTQP89FBirJ9M my wallet
![Снимок экрана (226)](https://user-images.githubusercontent.com/95878945/166716569-31457ec8-5b61-438a-85d7-9f9572067797.png)

**Comment by MonoAmumu** [comment]
![image](https://user-images.githubusercontent.com/56051943/166860919-896f097e-f871-4b08-8373-5a283b1e5dc3.png)


It's a different way of swapping, a unique way, I like unique things. Basilisk has something different!

**Comment by ronisalam** [comment]
`
![Screenshot (90)](https://user-images.githubusercontent.com/103059847/174398225-fbda26d4-f8d9-4743-b438-63f96d7b5475.png)

`-The UI platform has no problems, everything is fine, the style and graphics look comfortable too
-Performance is very fast and efficient, i love it
-a little advice, add a feature stake

bXmMZUUwjuyWCLzHfLE6evpAwrX4xNfaS6A4CChGSABRXhb6x

**Comment by Cubo25** [comment]
Closing this issue because no real bugs have been reported to the app.

Please visit our production website https://app.basilisk.cloud/#/ and try out once again to provide feedback.

Thanks
