### ISSUE TITLE
Add button "Max value"

### ISSUE THREAD

**Issue by Phantomoff1** [galacticcouncil/Basilisk-ui-old#956]
Hey there, my name is Arthur.
I propose to add a "Max value" button when exchanging coins so that people lose less time if they want to completely transfer one token to another. 
You also have a discord channel on your site. So add all social networks for convenience. 
People love simplicity. 
Thank you for your attention.

My wallet is below.

5ELfMbbLVe4Aq1C6HqVrRStdpxasNPobgqAYqy4noh4c9Bgc

**Comment by Cubo25** [comment]
![image](https://user-images.githubusercontent.com/8873699/183073398-0f26697a-479e-45dc-8168-350601ed2e92.png)

https://app.basilisk.cloud/#/

Max button already implemented. If you meant something else please provide further description.

Thanks
