### ISSUE TITLE
 (Screen)when switching pairs of tokens, for some pairs, it does not load the chart

### ISSUE THREAD

**Issue by Mozayka86** [galacticcouncil/Basilisk-ui-old#958]
When choosing aUSD-KSM tokens, the chart does not load
![Скриншот 2022-05-12 20 12 16](https://user-images.githubusercontent.com/105444945/168116180-aab94b90-9956-47c3-93ac-f77b4398a47f.png)

My wallet:
5Fc7y9gEWLwtk2ZKfKXyHDC4cFdNchjkGw9PCUs3NWK77xZf

**Comment by Cubo25** [comment]
Graph feature is not currently supported in our newest application. https://app.basilisk.cloud/#/wallet

This feature is planned for the future development.
