### ISSUE TITLE
Add The staking token and farming 

### ISSUE THREAD

**Issue by ditsyandrea22** [galacticcouncil/Basilisk-ui-old#963]
### Context

 bXh14FFopDqn2GmLYwnv4ZFBxjUCSJV3WEee5RhCJ3qH7j8Ng
adding for Likquid and Farm

### Possible Implementation

<!--- ![image](https://user-images.githubusercontent.com/34813777/169556270-b7d53f2e-0b4b-4d83-99a0-b3d235c3dddc.png)

**Comment by Cubo25** [comment]
We are currently working on these features. Please follow our discord channel in upcoming weeks for more info.
