### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by maht0rz** [galacticcouncil/Basilisk-ui-old#982]
- [x] loading state
- [ ] create task for double checking copywriting
- [x] vesting schedule end add tilde for approximate date
- [x] same tilde for days left
- [x] add state for disabled button, while a claim transaction is in progress (waiting to be included in the block) (this could be like a button loading state?)
- [ ] double check shown data with the story

**Comment by samborek** [comment]
@maht0rz  who shoud handle this? Can you guys assign people right away when its created?
